idf_component_register(
    SRCS
        "agent-presence-device.c"
        "font.c"
        "oled.c"
        "presence.c"
        "presence_layout.c"
        "presence_state.c"
        "message_handler.c"
        "wifi_connection.c"
        "http_server.c"
        "button.c"
    INCLUDE_DIRS "."
       
)
